package ledger

import (
	"crypto/x509"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"time"

	"github.com/hyperledger/fabric-gateway/pkg/client"
	"github.com/hyperledger/fabric-gateway/pkg/hash"
	"github.com/hyperledger/fabric-gateway/pkg/identity"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials"
)

// FabricConfig holds everything needed to connect to a peer via the Fabric
// Gateway. Paths point at the crypto material generated by the test network.
type FabricConfig struct {
	PeerEndpoint string // e.g. localhost:7051
	GatewayPeer  string // TLS server name, e.g. peer0.bmet.example.com
	MSPID        string // e.g. BMETMSP
	TLSCertPath  string // peer TLS CA cert
	CertPath     string // user signcert (PEM)
	KeyDir       string // user MSP keystore directory (single key file)
	Channel      string // e.g. anchor-channel
	Chaincode    string // e.g. employment-passport
}

// Fabric is a Ledger backed by a live Hyperledger Fabric network.
type Fabric struct {
	gw       *client.Gateway
	conn     *grpc.ClientConn
	contract *client.Contract
}

// NewFabric dials the peer, establishes a gateway identity, and returns a
// Ledger bound to the configured channel + chaincode.
func NewFabric(cfg FabricConfig) (*Fabric, error) {
	conn, err := newGRPCConn(cfg)
	if err != nil {
		return nil, err
	}
	id, err := newIdentity(cfg)
	if err != nil {
		return nil, err
	}
	sign, err := newSign(cfg)
	if err != nil {
		return nil, err
	}
	gw, err := client.Connect(id,
		client.WithSign(sign),
		client.WithHash(hash.SHA256),
		client.WithClientConnection(conn),
		client.WithEvaluateTimeout(5*time.Second),
		client.WithSubmitTimeout(15*time.Second),
	)
	if err != nil {
		conn.Close()
		return nil, fmt.Errorf("gateway connect: %w", err)
	}
	contract := gw.GetNetwork(cfg.Channel).GetContract(cfg.Chaincode)
	return &Fabric{gw: gw, conn: conn, contract: contract}, nil
}

func newGRPCConn(cfg FabricConfig) (*grpc.ClientConn, error) {
	pem, err := os.ReadFile(cfg.TLSCertPath)
	if err != nil {
		return nil, fmt.Errorf("read TLS cert: %w", err)
	}
	cert, err := identity.CertificateFromPEM(pem)
	if err != nil {
		return nil, fmt.Errorf("parse TLS cert: %w", err)
	}
	pool := x509.NewCertPool()
	pool.AddCert(cert)
	creds := credentials.NewClientTLSFromCert(pool, cfg.GatewayPeer)
	conn, err := grpc.NewClient(cfg.PeerEndpoint, grpc.WithTransportCredentials(creds))
	if err != nil {
		return nil, fmt.Errorf("grpc dial: %w", err)
	}
	return conn, nil
}

func newIdentity(cfg FabricConfig) (*identity.X509Identity, error) {
	pem, err := os.ReadFile(cfg.CertPath)
	if err != nil {
		return nil, fmt.Errorf("read signcert: %w", err)
	}
	cert, err := identity.CertificateFromPEM(pem)
	if err != nil {
		return nil, fmt.Errorf("parse signcert: %w", err)
	}
	return identity.NewX509Identity(cfg.MSPID, cert)
}

func newSign(cfg FabricConfig) (identity.Sign, error) {
	files, err := os.ReadDir(cfg.KeyDir)
	if err != nil || len(files) == 0 {
		return nil, fmt.Errorf("read keystore dir %s: %w", cfg.KeyDir, err)
	}
	pem, err := os.ReadFile(filepath.Join(cfg.KeyDir, files[0].Name()))
	if err != nil {
		return nil, fmt.Errorf("read private key: %w", err)
	}
	key, err := identity.PrivateKeyFromPEM(pem)
	if err != nil {
		return nil, fmt.Errorf("parse private key: %w", err)
	}
	return identity.NewPrivateKeySign(key)
}

func (f *Fabric) submit(fn string, args ...string) error {
	_, err := f.contract.SubmitTransaction(fn, args...)
	return err
}

func (f *Fabric) evaluate(fn string, args ...string) ([]byte, error) {
	return f.contract.EvaluateTransaction(fn, args...)
}

func (f *Fabric) RegisterDID(did, docHash string) error {
	return f.submit("RegisterDID", did, docHash)
}

func (f *Fabric) IssueCredential(credHash, schemaID, issuerDID, subjectDID, expiry string) error {
	return f.submit("IssueCredential", credHash, schemaID, issuerDID, subjectDID, expiry)
}

func (f *Fabric) RevokeCredential(credHash, reasonCode string) error {
	return f.submit("RevokeCredential", credHash, reasonCode)
}

func (f *Fabric) VerifyAnchor(credHash string) (*VerifyResult, error) {
	data, err := f.evaluate("VerifyAnchor", credHash)
	if err != nil {
		return nil, err
	}
	var res VerifyResult
	if err := json.Unmarshal(data, &res); err != nil {
		return nil, fmt.Errorf("decode VerifyAnchor: %w", err)
	}
	return &res, nil
}

func (f *Fabric) RecordDisclosure(consentHash, verifierDID string) error {
	return f.submit("RecordDisclosure", consentHash, verifierDID)
}

func (f *Fabric) SubmitCorroboration(credHash, sourceDID, evidenceHash string) error {
	return f.submit("SubmitCorroboration", credHash, sourceDID, evidenceHash)
}

func (f *Fabric) UpdateAgencyStanding(agencyDID string, delta int, evidenceHash string) error {
	return f.submit("UpdateAgencyStanding", agencyDID, strconv.Itoa(delta), evidenceHash)
}

func (f *Fabric) GetAgencyStanding(agencyDID string) (*AgencyStanding, error) {
	data, err := f.evaluate("GetAgencyStanding", agencyDID)
	if err != nil {
		return nil, err
	}
	var res AgencyStanding
	if err := json.Unmarshal(data, &res); err != nil {
		return nil, fmt.Errorf("decode GetAgencyStanding: %w", err)
	}
	return &res, nil
}

func (f *Fabric) CreateContract(contractHash, workerDID, employerDID string) error {
	return f.submit("CreateContract", contractHash, workerDID, employerDID)
}

func (f *Fabric) SignContract(contractHash, workerDID string) error {
	return f.submit("SignContract", contractHash, workerDID)
}

func (f *Fabric) ApproveContract(contractHash, employerDID string) error {
	return f.submit("ApproveContract", contractHash, employerDID)
}

func (f *Fabric) GetContract(contractHash string) (*ContractResult, error) {
	data, err := f.evaluate("GetContract", contractHash)
	if err != nil {
		return nil, err
	}
	var res ContractResult
	if err := json.Unmarshal(data, &res); err != nil {
		return nil, fmt.Errorf("decode GetContract: %w", err)
	}
	return &res, nil
}

func (f *Fabric) Close() error {
	if f.gw != nil {
		f.gw.Close()
	}
	if f.conn != nil {
		return f.conn.Close()
	}
	return nil
}
